apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: teamb
  description: Team B
spec:
  type: team
  profile:
    displayName: Team B
    email: teamb@acme.org
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Abby&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rprakashg@acme.org
spec:
  profile:
    displayName: Ram Gopinathan
    email: rprakashg@acme.org
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Gizmo&backgroundColor=transparent
  memberOf: [teamb]