name: ci
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
    branches:
      - main
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  add-target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: setup git
      run: |
        # Setting up the git config.
        git config --global user.email "rgopinat@redhat.com" # HARD CODING FOR NOW, NEED TO DETERMINE HOW TO RETRIEVE THIS FROM CURRENT USER CONTEXT
        git config --global user.name ${{ github.actor }}
    - id: add-target
      name: add a new target
      run: |
        TARGET_PATH=$(gh pr view $PR_NUMBER --json files --jq --jq '.files.[] | select (.path | contains("api.yaml")) | .path')
        echo $TARGET_PATH
        yq -i '.spec.targets += $TARGET_PATH' all-apis.yaml
    - name: commit changes to upstream
      run: |
        git add .          
        git commit -m "Updated all-apis.yaml to add new api path to targets"
        git push origin ${{ github.event.pull_request.head.ref }}
    - name: comment PR
      run: |
        # Use GitHub API to create a comment on the PR
        COMMENT="Added "
        
